import type { Metadata } from "next";
import { site } from "./site";

type PageMetaInput = {
  title: string;
  description: string;
  path: string;
  noIndex?: boolean;
};

// Generated by app/opengraph-image.tsx. Listed explicitly because a page's
// own openGraph block replaces the inherited one, image included.
const ogImage = (title: string, path: string) => ({
  // The home page uses the brand mark; every other page gets its own card.
  url: path === "/" ? "/opengraph-image" : `/og?page=${encodeURIComponent(path)}`,
  width: 1200,
  height: 630,
  alt: path === "/" ? "The Lawton Collection. Michelle Lawton, Cape Cod and the South Shore." : `${title}. Michelle Lawton, Cape Cod and the South Shore.`,
});

// Every route calls this so titles follow "Page · Michelle Lawton" and
// each page carries its own Open Graph block.
export function pageMeta({ title, description, path, noIndex }: PageMetaInput): Metadata {
  const fullTitle = `${title} · ${site.name}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_US",
      siteName: `${site.name} · ${site.brand}`,
      title: fullTitle,
      description,
      url: path,
      images: [ogImage(title, path)],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [ogImage(title, path).url] },
    robots: noIndex ? { index: false, follow: true } : undefined,
  };
}
